#
# This is configuration for golangci-lint (ex. gometalinter).
# It is designed to be opinionated and as strict as humanly possible.
# DO NOT DISABLE RULES WITHOUT A GOOD REASON!
#

[linters]
  enable-all = true
  disable = [
    # godox prohibits using FIXME/TODO in comments for no good reason
    "godox",

    # gomnd prohibits using magical numbers. In general, this is a good idea
    # but Gevulot is a low-level project and we have to use numbers extensively.
    # We can't move all of them into constants; it's just doesn't make sense.
    "gomnd",
  ]

[linters-settings]

  [linters-settings.funlen]
    lines = 120 # default 60