version: 2.1

workflows:
  version: 2

  "Run Tests":
    jobs:
      - run_linters:
          context: org-global

      - run_tests:
          context: org-global

      - build:
          context: org-global

jobs:
  run_linters:
    executor: run_with_gevolut_ci_image
    steps:
      - checkout
      - run:
          name: Run linters
          command: make lint

  run_tests:
    executor: run_with_gevolut_ci_image

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            mkdir -p $TEST_RESULTS
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/report.xml" EXIT
            make test VERBOSE=1 | tee ${TEST_RESULTS}/go-test.out

      - store_test_results:
          path: $TEST_RESULTS

  build:
    executor: run_with_gevolut_ci_image
    steps:
      - checkout
      - run:
          name: Run linter
          command: make build

executors:
  run_with_gevolut_ci_image:
    docker:
      - name: app
        image: docker.pkg.github.com/hired-test/docker-ci-images/ci-gevulot:latest
        auth:
          username: $GITHUB_PACKAGES_USER
          password: $GITHUB_PACKAGES_TOKEN
