package pg

// MessageField is used by ErrorResponseMessage and NoticeResponseMessage to store information about error / warning context.
type MessageField struct {
	// A code identifying the field type.
	Type MessageFieldType

	// The field value.
	Value string
}

// MessageFieldType identifies a field.
// Here are all known codes fo protocol v3: https://www.postgresql.org/docs/9.6/protocol-error-fields.html
type MessageFieldType byte

const (
	// Severity: the field contents are ERROR, FATAL, or PANIC (in an error message), or WARNING, NOTICE, DEBUG, INFO, or LOG (in a notice message), or a localized translation of one of these. Always present.
	MessageFieldSeverityLocalized MessageFieldType = 'S'

	// Severity: the field contents are ERROR, FATAL, or PANIC (in an error message), or WARNING, NOTICE, DEBUG, INFO, or LOG (in a notice message). This is identical to the S field except that the contents are never localized. This is present only in messages generated by PostgreSQL versions 9.6 and later.
	MessageFieldSeverity MessageFieldType = 'V'

	// Code: the SQLSTATE code for the error (see Appendix A). Not localizable. Always present.
	MessageFieldCode MessageFieldType = 'C'

	// Message: the primary human-readable error message. This should be accurate but terse (typically one line). Always present.
	MessageFieldMessage MessageFieldType = 'M'

	// Detail: an optional secondary error message carrying more detail about the problem. Might run to multiple lines.
	MessageFieldDetail MessageFieldType = 'D'

	// Hint: an optional suggestion what to do about the problem. This is intended to differ from Detail in that it offers advice (potentially inappropriate) rather than hard facts. Might run to multiple lines.
	MessageFieldHint MessageFieldType = 'H'

	// Position: the field value is a decimal ASCII integer, indicating an error cursor position as an index into the original query string. The first character has index 1, and positions are measured in characters not bytes.
	MessageFieldPosition MessageFieldType = 'P'

	// Internal position: this is defined the same as the P field, but it is used when the cursor position refers to an internally generated command rather than the one submitted by the client. The q field will always appear when this field appears.
	MessageFieldInternalPosition MessageFieldType = 'p'

	// Internal query: the text of a failed internally-generated command. This could be, for example, a SQL query issued by a PL/pgSQL function.
	MessageFieldInternalQuery MessageFieldType = 'q'

	// Where: an indication of the context in which the error occurred. Presently this includes a call stack traceback of active procedural language functions and internally-generated queries. The trace is one entry per line, most recent first.
	MessageFieldWhere MessageFieldType = 'W'

	// Schema name: if the error was associated with a specific database object, the name of the schema containing that object, if any.
	MessageFieldSchema MessageFieldType = 's'

	// Table name: if the error was associated with a specific table, the name of the table. (Refer to the schema name field for the name of the table's schema.)
	MessageFieldTable MessageFieldType = 't'

	// Column name: if the error was associated with a specific table column, the name of the column. (Refer to the schema and table name fields to identify the table.)
	MessageFieldColumn MessageFieldType = 'c'

	// Data type name: if the error was associated with a specific data type, the name of the data type. (Refer to the schema name field for the name of the data type's schema.)
	MessageFieldDataType MessageFieldType = 'd'

	// Constraint name: if the error was associated with a specific constraint, the name of the constraint. Refer to fields listed above for the associated table or domain. (For this purpose, indexes are treated as constraints, even if they weren't created with constraint syntax.)
	MessageFieldConstraint MessageFieldType = 'n'

	// File: the file name of the source-code location where the error was reported.
	MessageFieldFile MessageFieldType = 'F'

	// Line: the line number of the source-code location where the error was reported.
	MessageFieldLine MessageFieldType = 'L'

	// Routine: the name of the source-code routine reporting the error.
	MessageFieldRoutine MessageFieldType = 'R'
)
